FROM node:22-alpine

WORKDIR /app

ARG DEV_BACKEND_URL
ARG NEXT_PUBLIC_TOKEN_MERCADOPAGO
ARG NEXT_PUBLIC_VENTAS_URL

COPY package*.json ./

RUN npm install

COPY . .

ENV DEV_BACKEND_URL=$DEV_BACKEND_URL
ENV NEXT_PUBLIC_TOKEN_MERCADOPAGO=$NEXT_PUBLIC_TOKEN_MERCADOPAGO
ENV NEXT_PUBLIC_VENTAS_URL=$NEXT_PUBLIC_VENTAS_URL

RUN npm run build

EXPOSE 3000
    
CMD ["npm", "start"]
