apiVersion: v1
kind: Service
metadata:
  name: front-facturacion-service
spec:
  type: ClusterIP
  selector:
    app: front-facturacion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
